"""Add bot_reply column to chat_history table

Revision ID: 2b5da75b4e5b
Revises: 
Create Date: 2025-03-02 16:24:30.800415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b5da75b4e5b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bot_reply', sa.String(length=500), nullable=False))
        batch_op.drop_column('bot_response')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bot_response', sa.VARCHAR(length=500), nullable=False))
        batch_op.drop_column('bot_reply')

    # ### end Alembic commands ###
